import type { AboutContent } from "@/types/patricia-amorim";

export const about: AboutContent = {
  portrait: {
    src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/01-img-3815.jpg",
    alt: "image",
    width: 742,
    height: 733,
  },
  facts: [
    { label: "Location", value: "PERTH - Wa" },
    { label: "Born", value: "August 12, 1983" },
    { label: "Focus", value: "photography visual arts" },
  ],
  gallery: [
    {
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/02-dsc01636.jpg",
        alt: "profile-image",
        width: 4000,
        height: 2667,
      },
      venue: "Moores Building",
      year: "2023",
      description: [
        "Exhibition of the work (Re)Borrowing Arrows with Thatched Boats.",
        { tag: "br" },
        "Patricia Amorim in the foreground.",
        { tag: "br" },
        "In the background her work ",
        { tag: "a", href: "/exhibitions", children: ["Body Presence Identity"] },
      ],
    },
    {
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/03-thumbnail.jpg",
        alt: "",
        width: 1200,
        height: 1365,
      },
      venue: "ECU Galleries",
      year: "2023",
      description: [
        "Nexus Postgraduates showcases the creative works of candidates undertaking a Masters or PhD.",
      ],
    },
    {
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/04-patricialotus.jpg",
        alt: "",
        width: 1000,
        height: 771,
      },
      venue: "Museum of Sexual Diversity",
      year: "2019",
      description: [
        "My artistic composition is built through photographic media using the B&W (black and white) technique with parts of my body and projections of images from sites pertaining to my affective memory.",
      ],
    },
  ],
  awards: [
    {
      href: "https://www.artitute.com/cleanse-when-cleaning-becomes-an-act-of-care-control-and-resistance/",
      newTab: true,
      title: ["CLEANSE: When Cleaning Becomes an Act of Care, Control and Resistance"],
      caption: "Prestige Gallery - Singapore",
      year: "2026",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/05-cleanse-poster-724x1024.jpg",
        alt: "",
        width: 724,
        height: 1024,
      },
    },
    {
      href: "https://intellectdiscover.com/content/journals/10.1386/jaac_00074_1",
      newTab: true,
      title: ["Two approaches to cross-cultural exchange through shared arts practice"],
      caption: "Journal of Arts & Communities",
      year: "2026",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/06-journalofarts-communities.png",
        alt: "",
        width: 642,
        height: 911,
      },
    },
    {
      href: "https://creativematters.edu.au/methodologies-in-flux/",
      newTab: true,
      title: ["NiTRO + Creative Matters"],
      caption: "Perspectives on creative arts in higher education",
      year: "2025",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/07-nitro-creative-matters.jpg",
        alt: "",
        width: 1164,
        height: 1274,
      },
    },
    {
      href: "https://www.patriciaamorim.com/exhibitions/searching-my-work",
      newTab: true,
      title: ["Searching for My Work"],
      caption: "Spectrum project space residency",
      year: "2025",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/08-thumbnail.jpg",
        alt: "",
        width: 300,
        height: 200,
      },
    },
    {
      href: "https://www.patriciaamorim.com/exhibitions/ecu-postgraduate-show",
      newTab: true,
      title: ["ECU Postgraduate Show"],
      caption: "Hundred Names & Hopscotch Series",
      year: "2024",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/09-hopscotch-thumbnail.jpg",
        alt: "",
        width: 300,
        height: 200,
      },
    },
    {
      href: "https://acuads.com.au/conference/article/intersectionality-and-decolonisation-in-brazilian-and-australian-feminism/",
      newTab: true,
      title: ["Intersectionality and decolonisation"],
      caption: "2023 Conference",
      year: "2024",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/10-acuads.jpg",
        alt: "",
        width: 300,
        height: 298,
      },
    },
    {
      href: "https://creativematters.edu.au/palimpsest-series/",
      newTab: true,
      title: ["Creative Matters"],
      caption: "Perspectives on creative arts in higher education",
      year: "2024",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/11-site-creative-matters.jpg",
        alt: "",
        width: 725,
        height: 900,
      },
    },
    {
      href: "https://www.patriciaamorim.com/exhibitions/finding-our-place",
      newTab: false,
      title: ["Finding Our Place"],
      caption: "Hujiang Art Museum Shanghai",
      year: "2023",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/12-shanghai-exhibition-poster.jpg",
        alt: "",
        width: 1174,
        height: 653,
      },
    },
    {
      href: "https://www.patriciaamorim.com/exhibitions/re-borrowing-arrows",
      newTab: true,
      title: ["(Re)Borrowing Arrows with Thatched", { tag: "br" }, " Boats"],
      caption: "Moores Building Contemporary Art Space",
      year: "2023",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/13-moores-building-thumbnail.jpg",
        alt: "",
        width: 1200,
        height: 1834,
      },
    },
    {
      href: "https://www.patriciaamorim.com/exhibitions/nexus",
      newTab: true,
      title: ["Nexus Postgraduates"],
      caption: "Spectrum Project Space",
      year: "2023",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/03-thumbnail.jpg",
        alt: "",
        width: 1200,
        height: 1365,
      },
    },
    {
      href: "https://www.patriciaamorim.com/exhibitions/crossroads",
      newTab: true,
      title: ["Crossroads and Convergences"],
      caption: "Nyisztor Studio",
      year: "2023",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/14-crossroads-and-convergences-thumbnail.jpg",
        alt: "",
        width: 200,
        height: 133,
      },
    },
    {
      href: "https://www.patriciaamorim.com/exhibitions/here-now",
      newTab: true,
      title: ["Here|Now"],
      caption: "Spectrum Project Space",
      year: "2022",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/15-herenow23-spectrum-invite-v2-thumbnail.jpg",
        alt: "",
        width: 250,
        height: 250,
      },
    },
    {
      href: "https://www.patriciaamorim.com/exhibitions/collective",
      newTab: true,
      title: ["Collective"],
      caption: "Perth Centre For Photography",
      year: "2022",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/16-duplo-i.jpg",
        alt: "",
        width: 4000,
        height: 2667,
      },
    },
    {
      href: "https://acuads.com.au/conference/article/analysis-of-recent-feminist-literature-and-feminist-photographic-media-art-on-the-representation-of-the-gendered-body-in-a-cross-cultural-context/",
      newTab: true,
      title: [{ tag: "strong", children: ["Public Pedagogy: forms of ", { tag: "br" }, "togetherness"] }],
      caption: "ACUADS 2022 Conference",
      year: "2022",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/17-acuads.png",
        alt: "",
        width: 225,
        height: 225,
      },
    },
    {
      href: "https://www.nucleodoconhecimento.com.br/educacao/pedagogica-dos-docentes",
      newTab: true,
      title: ["Teachers’ pedagogical practice."],
      caption: "Multidisciplinary Scientific Journal Knowledge Center",
      year: "2021",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/18-revista-cientifica-multidisciplinar-nucleo-do-co.png",
        alt: "",
        width: 1280,
        height: 855,
      },
    },
    {
      href: "https://revistas.pucsp.br/index.php/aurora/article/view/33418",
      newTab: true,
      title: ["The relationship between the medium of photography and video in..."],
      caption: "Puc SP Magazines",
      year: "2018",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/19-cover-issue-2031-pt-br.jpg",
        alt: "",
        width: 420,
        height: 594,
      },
    },
    {
      href: "https://www.nucleodoconhecimento.com.br/education/identity-is-reflected",
      newTab: true,
      title: [
        {
          tag: "strong",
          children: ["How Ana Mendieta's crisis of identity is reflected in the siluetas series."],
        },
      ],
      caption: "Knowledge Scientific Nucleus Magazine",
      year: "2018",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/18-revista-cientifica-multidisciplinar-nucleo-do-co.png",
        alt: "",
        width: 1280,
        height: 855,
      },
    },
    {
      href: "https://www.researchgate.net/publication/376858343_BY-NC-ND_40_International_Fiction_and_reality_in_the_construction_of_gender_identities_in_the_human_portrait_digital_photography_Ficcao_e_realidade_na_construcao_de_identidades_de_genero_na_fotografia",
      newTab: true,
      title: [
        "International Fiction and reality in the construction of gender identities in the human portrait digital photography",
      ],
      caption: "Photo & Document Magazine no. two",
      year: "2016",
      image: {
        src: "/sites/www-patriciaamorim-com-6f0fd8c4/about-979bddc4/images/20-9c1f0d251f482559195ab2714befdc4e.jpg",
        alt: "",
        width: 879,
        height: 1000,
      },
    },
  ],
};
